apiVersion: v1
kind: Secret
metadata:
  name:  "{{ .Values.secret.name }}"
  namespace: "{{ .Values.namespace }}"
type: Opaque
data:
  username: {{ "admin" | b64enc }}
  password: {{ randAlphaNum 16 | b64enc }}
  token: {{ randAlphaNum 32 | b64enc }}